name: Release
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Automatic GitHub Release
                uses: justincy/github-action-npm-release@2.0.2
                id: release
